parameters:
#    testing_symfony_basics.example.class: TestingSymfony\BasicsBundle\Example

services:
#    testing_symfony_basics.example:
#        class: %testing_symfony_basics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
